export const GET_HOME_DATA = 'GET_HOME_DATA'

export const SET_SLIDEBAR_STATE = 'SET_SLIDEBAR_STATE'

export const GET_SEARCH_SUGGEST = 'GET_SEARCH_SUGGEST'

export const ADD_SEARCH_HISTORY = 'ADD_SEARCH_HISTORY'

export const RM_SEARCH_HISTORY = 'RM_SEARCH_HISTORY'

export const GET_RADIO = 'GET_RADIO'

export const ADD_MUSIC = 'ADD_MUSIC'

export const REMOVE_MUSIC = 'REMOVE_MUSIC'

export const PREV_MUSIC = 'PREV_MUSIC'

export const NEXT_MUSIC = 'NEXT_MUSIC'

export const SWITCH_MUSIC = 'SWITCH_MUSIC'